Kiosk/Bid Fulfillment/ConfirmYourBidArtsyLoginViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidPasswordViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidViewController.swift, Kiosk/Bid Fulfillment/FulfillmentContainerViewController.swift, Kiosk/Bid Fulfillment/PlaceBidViewController.swift, Kiosk/Bid Fulfillment/RegisterViewController.swift, Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift, KioskTests/Bid Fulfillment/ConfirmYourBidArtsyLoginViewControllerTests.swift, KioskTests/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewControllerTests.swift, KioskTests/Bid Fulfillment/ConfirmYourBidPINViewControllerTests.swift, KioskTests/Bid Fulfillment/ConfirmYourBidViewControllerTests.swift, KioskTests/Bid Fulfillment/FulfillmentContainerViewControllerTests.swift, KioskTests/Bid Fulfillment/PlaceBidViewControllerTests.swift, KioskTests/KioskTests.swift, KioskTests/ListingsViewControllerTests.swift
@orta I decided to just use one test suite-white storyboard that we use to instantiate view controllers.
=> @1aurabrown => Deprecates old style of instantiating view controllers in tests. 

Podfile, Podfile.lock
I've pushed the podspecs to Artsy's [Specs repo](https://github.com/artsy/Specs), so we can access them like normal pods without specifying a `:git` value.
=> @1aurabrown => Moved to font specs located in Artsy Specs repo.

Kiosk/App/MarkdownParser.swift, Podfile.lock
This is a WIP until @xing can take a look at https://github.com/xing/XNGMarkdownParser/pull/5 
Fixes #375.
=> @alloy => No longer render markdown links

Makefile
I found out that in the xcodebuild commands it is required to have `build test` instead of `test` for Xcode to launch the simulator.
Otherwise, if your build is taking longer than 2 minutes, it aborts because of the timeout.
As I saw in your Makefile your are just calling `test` so that might fix the problem described in https://github.com/artsy/eidolon/pull/379#issuecomment-74949058?
=> [Exploration] Build before test

Kiosk.xcodeproj/project.pbxproj, Kiosk/App/AppDelegate+GlobalActions.swift, Kiosk/App/BidderDetailsRetrieval.swift, Kiosk/App/Networking/ArtsyAPI.swift, Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift, Kiosk/Supporting Files/Info.plist, Makefile, Podfile, Podfile.lock
Fixes #357. Obviously still a work in progress :)
@katarinabatina Between the user entering their email and us showing a confirmation screen, there is going to be a delay (we need to get a confirmation from the API about whether or not this user is even registered). What should we show in the interim? Might last anywhere from 100ms to several seconds, depending on network connection speed. Maybe something like [this](https://github.com/TransitApp/SVProgressHUD)?
Next steps:
=> @orta => Bidder Details Notification

KioskTests/Bid Fulfillment/KeypadViewModelTests.swift
Same tests, just without `toEventually`.
=> @1aurabrown => Removes more uses of toEventually()

Kiosk/Auction Listings/ListingsViewController.swift, KioskTests/ListingsViewControllerTests.swift
We were never actually hitting the network, but we were also ignoring the `forceSync` property. I replaced it with a closure that logs the syncing behaviour, which is overridden with an empty closure during tests. Also cleaned up a few extraneous brackets. 
Fixes #390.
=> @orta => Fixes synching during tests.

Kiosk/App/Models/Image.swift, Kiosk/Bid Fulfillment/LoadingViewController.swift, Kiosk/Supporting Files/Info.plist, docs/CHANGELOG.md
We don't want to confuse users by having a button entitled "Cancel" on a confirmation screen. 
This needs:
- Better abstraction in the long-term (#406)
- Regenerated snapshots, that I can't do since I don't have the 8.1 simulator at home and my internet is :dog: slow (#405)
Fixes #373, and a small typo.
=> @orta => Fixes messaging surrounding cancel/back button titles

Kiosk/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewController.swift, docs/CHANGELOG.md
Basically what we do now is end the subscription (the binding) whenever the command sends `true` on `executing`, indicating that it has started executing (we ignore `false`). Since the first invocation of the command necessarily moves to one of two new controllers, we should be good :shipit: 
Fixes #444.
=> @orta => Fixes crash

fastlane/Appfile
Please test it first, but if the name is provided correctly, there is no need to provide the ID.
=> Removed `team_id` as `team_name` is provided already

Kiosk/App/AppDelegate.swift, Kiosk/Storyboards/UIStoryboardExtensions.swift
Thanks to eidolon project I discovered ```sbconstants``` command, and it looks really interesting to be aware of changes in storyboards identifiers.
Using that identifiers instead of "raw strings", do that when they change, compiler tell us that something was wrong, so it's better to use these identifiers.
=> Use StoryboardNames enum to identify storyboards instead of 'hardcoded strings'

Kiosk/App/Models/SaleArtwork.swift, Kiosk/Sale Artwork Details/SaleArtworkDetailsViewController.swift, KioskTests/Models/SaleArtworkTests.swift
This is tricky. Fixes #456.
Basically, this PR only "fixes" the problem _if_ the number of bids stayed the same but the reserve changed, which doesn't seem likely. Additionally, the code path that updates the highest bid (that is definitely happening) is the same path that updates the reserve status, so for my hypothesis to be correct, the model returned from the API must have the wrong reserve status anyway, which is super unlikely. 
But, I added some tests and fixed an incidental bug, so submitting.
> Note: CI is going to fail, since Travis and Circle are both flailing.
=> @sarahscott => corrects reserve state

Kiosk.xcodeproj/project.pbxproj, Kiosk/Bid Fulfillment/ManualCreditCardInputViewController.swift, Kiosk/Bid Fulfillment/ManualCreditCardInputViewModel.swift, Kiosk/Storyboards/Auction.storyboard, KioskTests/Bid Fulfillment/ManualCreditCardInputViewControllerTests.swift, KioskTests/Bid Fulfillment/ManualCreditCardInputViewModelTests.swift, docs/CHANGELOG.md
Crus is that we weren't sending a "complete" event to our `finishedSignal` once the CC tokenization succeeded. I added tests to ensure that the event is sent if and only if the tokenization succeeds. 
I also noticed a few other problems that I fixed and added test for, in separate commits. Should I make things like that separate PRs? Open to advice.
(Note: Circle and Travis are currently both failing to run tests. I've checked that they pass locally.)
Fixes #455.
=> @alloy => Manual CC Entry Problem 📱

Kiosk.xcodeproj/project.pbxproj, Kiosk/App/NSErrorExtensions.swift, Kiosk/Bid Fulfillment/LoadingViewController.swift, Kiosk/UIView+LongPressDisplayMessage.swift, docs/CHANGELOG.md
Adds a tap gesture recognizer to the error details label that will display an alert with the technical details, including the API response HTTP status code (if any), body length, and UTF8-encoded body string (if any).
I've produced an intentional error to generate the screenshot below:
Tests pass locally.
Fixes #454.
=> @alloy => Adds long tap gesture for bidding error details 📱

Kiosk/App/Models/Artwork.swift, Kiosk/App/Models/SaleArtwork.swift, KioskTests/Models/ArtworkTests.swift, KioskTests/Models/SaleArtworkTests.swift
I realize that I made an error on [this pull request](https://github.com/artsy/eidolon/pull/477). Artworks that were sold when the app first sync'd would be marked as sold, but artworks that were updated after the first sync would not. 
I don't think it needs a changelog entry since we've not released since the PR was merged. My bad for not thinking of this scenario at the time.
=> @orta => Updates existing artworks sold status

CHANGELOG.yml, Kiosk/App/Models/SaleArtwork.swift, KioskTests/Models/SaleArtworkTests.swift
I went looking on Google for "art auction" GIFs and was happy to see we're on the first page:
/cc @dblock 
Fixes #474.
=> @orta: Adds new backend estimateCents field to SaleArtwork model

CHANGELOG.yml, Kiosk/App/Models/SaleArtworkViewModel.swift, Kiosk/Auction Listings/ListingsViewModel.swift, KioskTests/ListingsViewModelTests.swift
This fixes a bug tracked in [this Trello card](https://trello.com/c/f3GvqhJl/82-kiosk-sync-using-wrong-lot-numbers). Here's what was going on:
- We had an auction that changed the original lot numbers. 
- The initial sync displayed the correct lot details. 
- Subsequent syncs would show incorrect details. 
Here's what I think was happening (@devangt is going to confirm this afternoon):
1. On first sync, the lengths of the new sale artworks and current sale artworks differ (the latter is empty), so we just use the new data. 
2. On subsequent syncs, we checked if the arrays lengths differed (let's assume they don't). We were then sorting the new/current sale artworks by `id`, then marching through the two arrays (of equal length). If the `id`s at each index matched, then we updated the …
=> @orta: Lot number fix

CHANGELOG.yml, Kiosk.xcodeproj/project.pbxproj, Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift, Kiosk/Bid Fulfillment/FulfillmentNavigationController.swift, KioskTests/Bid Fulfillment/ConfirmYourBidPINViewControllerTests.swift, KioskTests/Bid Fulfillment/FulfillmentNavigationControllerTests.swift
This fixes log in with bidder/phone number and pin. The issue was that the XApp token requested and stored by the original provider wasn't being added for providers created for logged-in users. This didn't affect users logged in with Artsy credentials because they had their own auth done with username/password which is separate from the trust token endpoint. 
This still needs tests, so it's WIP for now.
=> [WIP] @acjay: Fixes PIN login failures

Kiosk/Bid Fulfillment/BidderNetworkModel.swift
We set the single-use CC token to `nil` after it's been used. Seems obvious now that I say it out loud.
=> @acjay: Only adds a CC token once.

Kiosk/App/CardHandler.swift, Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift, KioskTests/CardHandlerTests.swift
Removes some dead code, removes reference cycles, and terminates signal when the VC disappears (cancelling or using a test CC token would make the signal persist, forever).
=> @orta: Reader Updates

.travis.yml
According [to the docs](http://docs.travis-ci.com/user/caching/), dependency caching doesn't work automatically if you specify a custom install step (which we do). So we need to specify the directory instead. 
I'm omitting CocoaPods caching because the cache is accessible to _all_ pull requests, and caching our Pods would cache our Keys, possibly exposing our API keys to a knowledgeable attacker.
=> @orta: Uses bundler caching

CHANGELOG.yml, Kiosk.xcodeproj/project.pbxproj, Kiosk/App/Networking/ArtsyAPI.swift, Kiosk/Auction Listings/ListingsViewModel.swift, Kiosk/Bid Fulfillment/BidderNetworkModel.swift, Kiosk/Bid Fulfillment/LoadingViewModel.swift, Kiosk/Bid Fulfillment/Models/NewUser.swift, KioskTests/Bid Fulfillment/BidderNetworkModelTests.swift, KioskTests/Bid Fulfillment/LoadingViewModelTests.swift, KioskTests/Bid Fulfillment/RegistrationPasswordViewModelTests.swift, KioskTests/ListingsViewControllerTests.swift, KioskTests/ListingsViewModelTests.swift
If a new user is outbid, we allow them to increase their bid or "Continue" to view credentials. If they _did_ increase their bid, they'd never be shown those credentials because we were persisting the state of "newly registered" in a view model that never got forwarded. 
This should also address the CI issues we've been having – too many never-terminated recurring signals :sweat_smile:
=> @orta: Fixes problem not displaying credentials

CHANGELOG.yml, Kiosk/Auction Listings/ListingsViewModel.swift
Replicates logic from here: https://github.com/artsy/eidolon/blob/49e798a272727869dabb71a0e4755891fb1c0679/Kiosk/App/Models/SaleArtworkViewModel.swift#L72-L75 I think we should move these into some sort of computed property on `SaleArtwork` or `SaleArtworkViewModel`, but this works for now. 
Fixes bug tracked in Trello: https://trello.com/c/E5faR3wq/169-kiosk-lots-that-had-bids-retracted-are-still-listed-under-highest-bids-as-if-they-still-have-a-bid
=> @acjay: Discounts retracted single bids from sorting.

CHANGELOG.yml, Kiosk.xcodeproj/project.pbxproj, Kiosk/App/AppViewController.swift, Kiosk/Auction Listings/ListingsViewController.swift, Kiosk/Bid Fulfillment/LoadingViewController.swift, Kiosk/Bid Fulfillment/LoadingViewModel.swift, Kiosk/UIViewController+Bidding.swift
Adds more details to analytics events (like which artwork someone is interested in).
As requested on Trello: https://trello.com/c/P9cUr8Af/172-track-current-urls-artworks-for-bids-either-clicked-or-confirmed-in-kiosks-only-user-id-is-tracked
=> @orta: Shores up analytics details

Kiosk/App/Networking/Networking.swift
Hey @ashfurrow and co, really enjoying watching [the code review](https://artsy.github.io/blog/2016/01/14/eidolon-code-review/)! Thanks for posting it, really interesting! :smiley:
Noticed a tiny typo.
=> Tiny Typo: fix “wait unti” ➜ “wait until”.

fastlane/Fastfile
When I ran `fastlane oss`, it stopped after `ArtsyAPIClientSecret` is saved:
```sh
% be fastlane oss
[13:27:58]: -------------------------------------------------
[13:27:58]: --- Step: Verifying required fastlane version ---
[13:27:58]: -------------------------------------------------
[13:27:58]: fastlane version valid
[13:27:58]: Driving the lane 'oss' 🚀
[13:27:58]: -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Ensure to add project name to cocoapods-keys command

CHANGELOG.yml, Kiosk/Bid Fulfillment/BidderNetworkModel.swift, Kiosk/Bid Fulfillment/LoadingViewController.swift, Kiosk/Bid Fulfillment/LoadingViewModel.swift, KioskTests/Bid Fulfillment/BidderNetworkModelTests.swift
This is a fix for a problem tracked in Trello: https://trello.com/c/Bio2jZQe/297-kiosk-showstopper-bid-polling-for-resolving-high-bidder-status-failing#
The issue is that bids weren't being placed (unless you were also registering, strangely). Actually this makes sense, once the underlying issue was found. 
We were sending `empty()` as a result of "we don't need to do this piece of work", and then trying to `flatMap` that empty observable to the bid-placing network call. But empty observables don't have anything to `flatMap` against, they're empty. So instead, now we're sending `just()`, which is short for `just(Void())`, which is a value (an empty one). So that value can get `flatMap`'d appropriately.
tl;dr we were returning an empty observable instead of an observable that sends an …
=> Fixes bid resolution problems

CHANGELOG.yml, Kiosk/App/Models/Image.swift
[This](https://www.artsy.net/artwork/d-star-face-work-on-paper-number-5) artwork is too tall, and throws off our masonry layout. This isn't the first time it's happened, so I repurposed the old hack, and updated with a link to how we plan to deal with this longterm. 
Before:
Notice how blurry it is. 
After:
Much nicer.
=> Workaround for tall image

Kiosk/App/Networking/Networking.swift, Kiosk/Observable+Operators.swift
`typealias` usage inside protocols is deprecated in Swift 2.2 and will be removed in Swift 3 according to [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0011-replace-typealias-associated.md). `associatedtype` should be use instead.
=> Changes typealias to associatedtype inside protocols

README.md
The `README` still stated you need to use `Xcode 7`, as the project is Swift 2. As the project is now using Swift 3, this should be `Xcode 8`.
=> Update README getting started to Swift 3

CHANGELOG.yml, Kiosk/App/Models/Sale.swift, Kiosk/Auction Listings/ListingsCountdownManager.swift, KioskTests/Models/SaleTests.swift
Live auctions (which the Kiosk doesn't support but does list) now have optional end dates. This fixes a crash when looking at the auction list in the Admin menu if there were a live sale listed there.
=> Sale list crash fix

docs/overview.md
`imperitive` -> `imperative`
`awkard` -> `awkward `
=> Fixes typos in docs/overview.md

CHANGELOG.yml, Kiosk/Admin/AdminCardTestingViewController.swift, Kiosk/App/CardHandler.swift, Podfile, Podfile.lock
Newer card readers weren't "connecting", so this changes it and adds a few other improvements. They're now reading the card, but not able to tokenize them. I've opened [an issue](https://github.com/CardFlight/cardflight-ios/issues/72) to ask for help.
Fixes https://github.com/artsy/eidolon/issues/658
=> Defaults to unknown reader type, logging improvements.

CHANGELOG.yml, Kiosk/App/CardHandler.swift, Podfile, Podfile.lock
Version 3.6 fixes a problem with newer card readers, no reason we shouldn't be on the latest and greatest.
=> Updates CardFlight SDK

CHANGELOG.yml, Kiosk/App/AppDelegate+GlobalActions.swift, Kiosk/App/BidderDetailsRetrieval.swift, Kiosk/App/Models/SystemTime.swift, Kiosk/App/SwiftExtensions.swift, Kiosk/Auction Listings/ListingsViewController.swift, Kiosk/Auction Listings/ListingsViewModel.swift, Kiosk/Bid Fulfillment/BidCheckingNetworkModel.swift, Kiosk/Bid Fulfillment/BidderNetworkModel.swift, Kiosk/Bid Fulfillment/ConfirmYourBidArtsyLoginViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift, Kiosk/Bid Fulfillment/ConfirmYourBidViewController.swift, Kiosk/Bid Fulfillment/FulfillmentNavigationController.swift, Kiosk/Bid Fulfillment/ManualCreditCardInputViewModel.swift, Kiosk/Bid Fulfillment/RegistrationEmailViewController.swift, Kiosk/Bid Fulfillment/RegistrationMobileViewController.swift, Kiosk/Bid Fulfillment/RegistrationPasswordViewController.swift, Kiosk/Bid Fulfillment/RegistrationPasswordViewModel.swift, Kiosk/Bid Fulfillment/RegistrationPostalZipViewController.swift, Kiosk/Bid Fulfillment/YourBiddingDetailsViewController.swift, Kiosk/ListingsCollectionViewCell.swift, Kiosk/Observable+Operators.swift, Kiosk/Sale Artwork Details/SaleArtworkDetailsViewController.swift, KioskTests/App/SwiftExtensionsTests.swift, KioskTests/ListingsViewControllerTests.swift, Podfile, Podfile.lock
This fixes #587 by moving our own functions to a pod that already contains them (Eidolon was the inspiration for the pod) and also cleans up our use of RxSwift. Specifically, it removes the custom `doOnNext`, `doOnError`, and `doOnCompleted` functions and replaces their use with the standard `do(onNext:onError:onCompleted:)` operator. Finally, it fixes some intermittently failing snapshot tests (see note left in file).
=> Moves to RxOptional and cleans up RxSwift use

Kiosk/App/Networking/ArtsyAPI.swift, Kiosk/App/Networking/Networking.swift, Kiosk/Bid Fulfillment/Models/BidDetails.swift, KioskTests/App/ArtsyProviderTests.swift, KioskTests/Bid Fulfillment/AdminCCBypassNetworkModelTests.swift, KioskTests/Bid Fulfillment/PlaceBidNetworkModelTests.swift, KioskTests/Bid Fulfillment/RegistrationPasswordViewModelTests.swift, KioskTests/ListingsViewModelTests.swift, Podfile, Podfile.lock
Continues #669.
Eidolon has always been used as the role model app in the Moya community and is constantly used as an example when people are looking for good practices. As a way to thank you folks for the good work, I went ahead and migrated Eidolon to the new major release of Moya :wink:
Some of the changes were done by @ashfurrow in #669, which I rebased against `master` and fixed some conflicts in `Podfile` and `Podfile.lock`. The changelog was also out of sync, but as I wasn't sure about the entries I just took them off for now. That's one thing pending.
I may have missed some *improvements* as I was mostly focused in getting Eidolon to work with Moya 9.0. The [Migration Guide on Moya](https://github.com/Moya/Moya/blob/master/docs/MigrationGuides.md) may have some new things that …
=> Moya 9.0 migration

CHANGELOG.yml, Kiosk/App/Networking/ArtsyAPI.swift, Kiosk/Bid Fulfillment/Models/BidDetails.swift, Kiosk/Bid Fulfillment/Models/RegistrationCoordinator.swift, Kiosk/Bid Fulfillment/RegisterViewController.swift, Podfile.lock
Funny story! There's been a longstanding bug somewhere, which I will try to track down, but this fixes it. Eidolon has been specifying JSON encoding of request parameters for some time, but has been URL encoding them for GET/PUT requests (we only want JSON encoding for POST bodies). Somewhere, probably in Alamofire, the behaviour changed so if you specify JSON encoding, it _always_ encodes a HTTP body with JSON, even for GET requests. This confuses our API, so I've changed it to use JSON only for POST requests. This was a tricky one to track down – using the built-in `NetworkLoggerPlugin` with cURL printing helped a lot.
Additionally, there was a cycle in RxSwift where a Variable was being set inside a subscribe block that executes when the Variable changes. Kind of a weird one, not sure …
=> Cleanup from RxSwift+Moya upgrades 📱

Gemfile.lock
This updates the Nokogiri dependency, relied upon for Eidolon's deploy script and CI, to avoid a security vulnerability.
=> Updates Nokogiri to avoid security vulnerability #trivial

README.md
=> Removes Xcode 8 / Swift 3 specifier.

Kiosk.xcodeproj/project.pbxproj, Kiosk/Admin/AdminCardTestingViewController.swift, Kiosk/App/AppDelegate.swift, Kiosk/App/CardHandler.swift, Kiosk/App/GlobalFunctions.swift, Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift, Kiosk/Storyboards/Fulfillment.storyboard, Kiosk/Supporting Files/Info.plist, Kiosk/Supporting Files/PodsBridgingHeader.h, KioskTests/Bid Fulfillment/KeypadViewModelTests.swift, KioskTests/CardHandlerTests.swift, Podfile, Podfile.lock
This PR unblocks work on our [Q4 Kiosk Updates](https://artsyproduct.atlassian.net/browse/PURCHASE-511).
This reverts #687. See [this Jira ticket](https://artsyproduct.atlassian.net/browse/PURCHASE-615) for more info. We need to build against Xcode 9 because Xcode 10 removes libstdc++.6.0.9 and CardFlight v3 requires it to link against. To that end, I'm merging into the `Xcode-9` branch, which can run parallel to `master` for now.
In the mean time, this PR also includes a fix for the initial problem that prompted me to upgrade to CardFlight 4: 
https://github.com/artsy/eidolon/commit/2a2a48f521c82add23de26dbdb746c71df7f9f2d
=> Fixes CardFlight integration

CHANGELOG.yml, Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift
CI isn't going to run, but this works locally 👍 Shouldn't have to change this again for another ten years 😉
=> Fixes stubbed CC tokenization

CHANGELOG.yml, Kiosk/Bid Fulfillment/Models/RegistrationCoordinator.swift, Kiosk/Bid Fulfillment/RegisterViewController.swift, KioskTests/Models/RegistrationCoordinatorTests.swift
This PR follows-up on #708. That PR had the "name" view present in the side bar, but the user was never actually _asked_ for their name.
That's because we're calculating whether or not the "name" should be asked for in two places: 
- Where the side bar UI is rendered.
- Where the user is guided through our registration flow (the `RegistrationCoordinator` class).
Ideally we would only have this calculated once, but it's a larger refactor than I want to take on right now. I did, however, clean up the `nextViewControllerForBidDetails` function to no longer take a `sale` param (because `RegistrationCoordinator` already has a `sale` property).
=> [PURCHASE-1292] Name entry fix for manual CC input

Podfile
You should use CDN for public pod spec after cocoapods 1.7.2
=> change public spec source to CDN

Kiosk/App/Models/Artwork.swift
An open source contributor [brought up a problem](https://github.com/ashfurrow/xcode-hardware-performance/pull/137#issue-527887411) where the OSS font-loading wasn't working (ie: the font is returning `nil`) and our code does not expect that. I tried debugging this but the iOS font pod closed-vs-open fonts are notoriously hard for Artsy staff to debug because of how we determine if someone "should" have the closed fonts ([see code here](https://github.com/artsy/Artsy-OSSUIFonts/blob/master/Pod/Scripts/ArtsySetup.rb)). So instead, I looked for places where we were force-unwrapping these fonts and added code to make sure that we handle the `nil`s correctly.
CI might not pass on this but the PR should be safe to merge – I tested locally.
/cc @jlnr @ondrejhanak
=> fix: handles nil fonts correctly for OSS contributors #trivial
