artsy/eidolon

- Gemfile
- Gemfile.lock
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/AppDelegate.swift
- Kiosk/App/AppViewController.swift
- Kiosk/App/CardHandler.swift
- Kiosk/App/Logger.swift
- Kiosk/Auction Listings/ListingsViewController.swift
- Kiosk/Bid Fulfillment/BalancedManager.swift
- Kiosk/Bid Fulfillment/BidderNetworkModel.swift
- Kiosk/Bid Fulfillment/ConfirmYourBidArtsyLoginViewController.swift
- Kiosk/Bid Fulfillment/PlaceBidNetworkModel.swift
- KioskTests/App/LoggerTests.swift
- Makefile
- Podfile
- Podfile.lock
- README.md
This cleans up a lot of things, particularly surrounding pods that are now on trunk. I opted to write our own logger because we only need it to be very simple – all of the existing solutions were overkill imo.
> @orta => Cleanup

- Gemfile
- Gemfile.lock
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/Admin/AdminCardTestingViewController.swift
- Kiosk/App/AppDelegate.swift
- Kiosk/App/Networking/APIKeys.swift
- Kiosk/Bid Fulfillment/ManualCreditCardInputViewController.swift
- Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift
- Kiosk/Supporting Files/Info.plist
- Kiosk/Supporting Files/PodsBridgingHeader.h
- KioskTests/ArtsyAPISpec.swift
- Podfile
- Podfile.lock
- docs/deployment.md
Submitting work as I accomplish it. I'm doing some unrelated pair programming tomorrow, so it may be Tuesday before another commit. 
Gonna depend on https://github.com/orta/cocoapods-keys/pull/31 , too. 
Fixes #343.
> [WIP] @orta => Deploy with CocoaPods

- Kiosk/App/AppViewController.swift
- Kiosk/Auction Listings/ListingsCountdownManager.swift
- Kiosk/Supporting Files/Info.plist
A few small issues related to labels and their fonts. Also cleans up the `info.plist`, since our fonts pod is no longer linked statically. 
Fixes #364. 
Fixes #287.
> @orta => Fixes some label issues

- KioskTests/AppViewControllerTests.swift
- KioskTests/Bid Fulfillment/ConfirmYourBidArtsyLoginViewControllerTests.swift
- KioskTests/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewControllerTests.swift
- KioskTests/Bid Fulfillment/ConfirmYourBidPINViewControllerTests.swift
- KioskTests/Bid Fulfillment/ConfirmYourBidViewControllerTests.swift
- KioskTests/Bid Fulfillment/LoadingViewControllerTests.swift
- KioskTests/Bid Fulfillment/PlaceBidViewControllerTests.swift
- KioskTests/ListingsViewControllerTests.swift
- KioskTests/RegisterFlowViewTests.swift
- KioskTests/SaleArtworkDetailsViewControllerTests.swift
Gotta get my PR for the day in, since I spent most of today working on tax forms. 
Fixes #377.
> @orta => Sut Replacement

- Kiosk/App/AppDelegate+GlobalActions.swift
- Kiosk/Help/HelpAnimator.swift
- Kiosk/Help/HelpViewController.swift
> @1aurabrown => Tapping outside the help menu dismiss it

- Gemfile
- Gemfile.lock
- Podfile
- Podfile.lock
Updates to latest (and greatest) CocoaPods release.
> @orta => CocoaPods update

- .travis.yml
> @orta => Removed pod repo command from CI config

- Gemfile.lock
- fastlane/.env
- fastlane/Fastfile
Less `sh` and more using build-in actions. 
Was just waiting on https://github.com/KrauseFx/fastlane/pull/175
> @alloy => Made Fastfile more awesome.

- Kiosk/Auction Listings/ListingsViewController.swift
This is really difficult to test, but this view controller is my main target for https://github.com/artsy/eidolon/issues/333 , and I promise to test it then :heart: 
Fixes #331.
> @orta => Removes RACSubject use in paging code

- Gemfile.lock
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/AppDelegate.swift
- Kiosk/App/AppViewController.swift
- Kiosk/App/GlobalFunctions.swift
- Kiosk/App/Networking/ArtsyAPI.swift
- Kiosk/App/Networking/XAppAuthentication.swift
- Kiosk/App/ReachabilityManager.swift
- Kiosk/Auction Listings/ListingsViewController.swift
- Kiosk/Bid Fulfillment/ConfirmYourBidViewController.swift
- Kiosk/Help/HelpViewController.swift
- KioskTests/App/ArtsyProviderTests.swift
- KioskTests/ListingsViewControllerTests.swift
- KioskTests/TestHelpers.swift
This fixes #258. But I figured, why stop at the listings controller? 
So I used signal chaining to require network operations to be online first, in the same way we make sure we have a valid XApp token.
> @orta => Network requests online while online

- Gemfile
- Gemfile.lock
> [Gemfile] Update CocoaPods to 0.37.0.beta.1

- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/RACExtensions.swift
- Kiosk/Bid Fulfillment/RegistrationEmailViewController.swift
- Kiosk/Bid Fulfillment/RegistrationMobileViewController.swift
- Kiosk/Bid Fulfillment/RegistrationPasswordViewController.swift
- Kiosk/Bid Fulfillment/RegistrationPostalZipViewController.swift
- Kiosk/Bid Fulfillment/SwipeCreditCardViewController.swift
- KioskTests/App/RACExtensionsTests.swift
- KioskTests/Bid Fulfillment/ManualCreditCardInputViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationEmailViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationMobileViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationPasswordViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationPostalZipViewControllerTests.swift
- KioskTests/Bid Fulfillment/SwipeCreditCardViewControllerTests.swift
If you have an idea for a better abstraction for these tests, I'd love to implement it. 
Fixes #441.
> @orta => Fixes crash with re-binding signals

- fastlane/Fastfile
- fastlane/README.md
Added initial version of `fastlane docs`
You can update the text in the `fastlane/Fastfile` and run `fastlane docs` :+1:
> Added fastlane docs

- README.md
> @ashfurrow => Project Status: Featured in Vogue

- README.md
Need to let people know we're approachable.
> @orta => Adds Questions section to readme

- CHANGELOG.yml
- Kiosk/Sale Artwork Details/SaleArtworkDetailsViewController.swift
> @orta: Displays thumbnail on detail view while fullsize image is being downloaded

- CHANGELOG.yml
- Kiosk/Auction Listings/TableCollectionViewCell.swift
> @orta: Tapping anywhere in the list cell pushes the detail VC

- CHANGELOG.yml
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/Networking/ArtsyAPI.swift
- Kiosk/Bid Fulfillment/BidCheckingNetworkModel.swift
- Kiosk/Bid Fulfillment/BidderNetworkModel.swift
- Kiosk/Bid Fulfillment/FulfillmentNavigationController.swift
- Kiosk/Bid Fulfillment/LoadingViewController.swift
- Kiosk/Bid Fulfillment/LoadingViewModel.swift
- Kiosk/Bid Fulfillment/PlaceBidNetworkModel.swift
- Kiosk/Bid Fulfillment/RegisterViewController.swift
- KioskTests/Bid Fulfillment/LoadingViewControllerTests.swift
- KioskTests/Bid Fulfillment/LoadingViewModelTests.swift
I saw a user do it at an auction once – it makes sense – it's the only saturated part on the screen, and she had been bidding already. Power user I guess :smile: 
Fixes #427.
> @orta: Lets users dismiss bid confirmation view by tapping checkmark

- README.md
Just a quick typo fix.
Thanks for taking the time to develop the app out in the open - insanely valuable for people (like myself) coming up to speed on Swift.
> Very small typo.

- Kiosk/App/UIViewControllerExtensions.swift
- Kiosk/Bid Fulfillment/FulfillmentContainerViewController.swift
- Kiosk/Bid Fulfillment/LoadingViewController.swift
- KioskTests/Bid Fulfillment/LoadingViewControllerTests.swift
- Podfile
- Podfile.lock
> @orta: Adds test for green checkmark dismissal

- Kiosk.xcodeproj/project.pbxproj
- Kiosk.xcodeproj/xcshareddata/xcschemes/Kiosk.xcscheme
- Kiosk/App/SwiftExtensions.swift
- Kiosk/Bid Fulfillment/ConfirmYourBidArtsyLoginViewController.swift
- Kiosk/Sale Artwork Details/SaleArtworkDetailsViewController.swift
- Kiosk/Supporting Files/Info.plist
- KioskTests/App/SwiftExtensionsTests.swift
- KioskTests/Info.plist
Also upgraded Kiosk project to Xcode's recommended settings.
Let me know what you think!
> @orta: Adds Optional isEmpty-ness.

- Kiosk/App/Networking/ArtsyAPI.swift
- Podfile
- Podfile.lock
Mostly surrounding Moya updates :tada:
> @orta: Removes unnecessary pods.

- fastlane/Fastfile
> @ashfurrow => Add a validation hook for OSS keys

- README.md
- docs/artsy_dev.md
Let me know if I can clarify anything.
> @acjay: Added Artsy setup instructions.

- Podfile
> Switch to Alan's computer user name in Podfile

- CHANGELOG.yml
- Gemfile
- Gemfile.lock
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/Networking/ArtsyAPI.swift
- Kiosk/App/Networking/NetworkLogger.swift
- Kiosk/Bid Fulfillment/BidderNetworkModel.swift
- Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift
- Kiosk/Bid Fulfillment/FulfillmentNavigationController.swift
- KioskTests/App/ArtsyProviderTests.swift
- KioskTests/Bid Fulfillment/ConfirmYourBidPINViewControllerTests.swift
- KioskTests/Bid Fulfillment/FulfillmentNavigationControllerTests.swift
- KioskTests/Bid Fulfillment/PlaceBidNetworkModelTests.swift
- KioskTests/Bid Fulfillment/RegistrationPasswordViewModelTests.swift
- KioskTests/ListingsViewModelTests.swift
- Podfile.lock
Most of the changes were updating Moya. Most of my time was fighting with the Swift compiler.
> @acjay: Adds network logging

- CHANGELOG.yml
- Kiosk.xcodeproj/project.pbxproj
- Kiosk/App/Models/SaleArtworkViewModel.swift
- KioskTests/ListingsViewModelTests.swift
- KioskTests/Models/SaleArtworkTests.swift
- KioskTests/Models/SaleArtworkVIewModelTests.swift
Corresponding Force PR here: https://github.com/artsy/force/pull/3623
Tracked in Trello: https://trello.com/c/Yzxh40ER/150-1-bid-for-cancelled-bids
CI will fail until #535 is merged.
> @orta: Displays 0 Bids for works with no highest bid

- CHANGELOG.yml
- Kiosk/Admin/AdminLogViewController.swift
- Kiosk/Admin/AdminPanelViewController.swift
- Kiosk/Storyboards/Auction.storyboard
Scroll to bottom on admin logs and shows the app version on the admin panel.
> @orta: Admin Improvements

- Kiosk/App/Models/SaleArtworkViewModel.swift
- Kiosk/Auction Listings/ListingsViewModel.swift
- Kiosk/Bid Fulfillment/BidCheckingNetworkModel.swift
- Kiosk/Bid Fulfillment/BidderNetworkModel.swift
- Kiosk/Bid Fulfillment/LoadingViewModel.swift
- Kiosk/Bid Fulfillment/PlaceBidNetworkModel.swift
- KioskTests/App/ArtsyProviderTests.swift
- KioskTests/AppViewControllerTests.swift
- KioskTests/ArtsyAPISpec.swift
- KioskTests/Bid Fulfillment/BidderNetworkModelTests.swift
- KioskTests/Bid Fulfillment/FulfillmentNavigationControllerTests.swift
- KioskTests/Bid Fulfillment/GenericFormValidationViewModelTests.swift
- KioskTests/Bid Fulfillment/LoadingViewModelTests.swift
- KioskTests/Bid Fulfillment/PlaceBidViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationEmailViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationMobileViewControllerTests.swift
- KioskTests/Bid Fulfillment/RegistrationPasswordViewControllerTests.swift
- KioskTests/Bid Fulfillment/StripeManagerTests.swift
- KioskTests/Bid Fulfillment/YourBiddingDetailsViewControllerTests.swift
- KioskTests/CardHandlerTests.swift
- KioskTests/HelpViewControllerTests.swift
- KioskTests/ListingsViewModelTests.swift
- KioskTests/Models/SaleArtworkTests.swift
- KioskTests/TestHelpers.swift
Unit tests are now compiling and completing, with twenty failures. I'll be looking at those next.
> [WIP] FRP Transition

- Kiosk/App/Models/Artwork.swift
- Kiosk/App/Models/SaleArtworkViewModel.swift
- Kiosk/Bid Fulfillment/ConfirmYourBidPINViewController.swift
- Kiosk/Bid Fulfillment/PlaceBidViewController.swift
This wraps up the code-golfing. On to testing! Or blogging or what-have-you.
> [⛳] Addresses feedback

- KioskTests/Bid Fulfillment/ManualCreditCardInputViewModelTests.swift
- Podfile.lock
- fastlane/README.md
Nimble had an issue with intermittent failures, like this one: https://travis-ci.org/artsy/eidolon/builds/107248693
Updating to 3.1.0 should fix it. Also, fastlane did something to its readme ¯\\_(ツ)_/¯
> Updates Nimble+Quick

- Kiosk/ListingsCollectionViewCell.swift
Instead of de-init based ones - fixes #591
Gonna take a quick stab at  tests now, if in a few hours there are none, that's probably cause I moved back to eigen auctions work.
> Use cell re-use based disposal bags for bindings on cells

- CHANGELOG.yml
- Kiosk/Bid Fulfillment/ConfirmYourBidEnterYourEmailViewController.swift
> Fixes crash when entering existing phone/email combo.

- Kiosk/App/Logger.swift
@ashfurrow you must have missed this in https://github.com/artsy/eidolon/commit/86d2fd2c2604e5e0bff6d8579b5a0e91af8fc70b
> Update Logger.swift to handle NSFileHandle throws

- Kiosk/Admin/AuctionWebViewController.swift
- Kiosk/App/Networking/Networking.swift
- Kiosk/App/Views/RegisterFlowView.swift
- Kiosk/App/Views/SwitchView.swift
- Kiosk/App/Views/Text Fields/TextField.swift
- Kiosk/Auction Listings/ListingsCountdownManager.swift
- Kiosk/Auction Listings/ListingsViewModel.swift
- Kiosk/Auction Listings/WebViewController.swift
- Kiosk/Bid Fulfillment/BidCheckingNetworkModel.swift
- Kiosk/Observable+Operators.swift
The purpose of this pull request is to fix some of the deprecation warnings.  Did not fix the curried deprecation warnings as some of the observables seem to be dependent on those functions.
> Fix deprecations

- CHANGELOG.yml
- Kiosk/App/Models/Image.swift
> Fix for tall images

- Kiosk/Supporting Files/PodsBridgingHeader.h
> Fixes conditional include's module and header name.

- CHANGELOG.yml
- Kiosk/Auction Listings/ListingsViewController.swift
- Kiosk/Bid Fulfillment/StripeManager.swift
- Kiosk/Storyboards/Fulfillment.storyboard
- KioskTests/Bid Fulfillment/StripeManagerTests.swift
> Fixes for recent deploy

- LICENSE
- README.md
I noticed that our copyright line was inconsistent across projects and
often still listed 2016. So, I worked with Yayoi to figure out what the
right language was and am now copy/pasting to achieve consistency.
> Update License section

- CHANGELOG.yml
- Kiosk/App/Models/Bid.swift
- Kiosk/App/Models/BidderPosition.swift
- Kiosk/App/Models/SaleArtwork.swift
- Kiosk/App/Models/SaleArtworkViewModel.swift
- Kiosk/Bid Fulfillment/BidDetailsPreviewView.swift
- Kiosk/Bid Fulfillment/KeypadContainerView.swift
- Kiosk/Bid Fulfillment/KeypadViewModel.swift
- Kiosk/Bid Fulfillment/Models/BidDetails.swift
- Kiosk/Bid Fulfillment/PlaceBidNetworkModel.swift
- Kiosk/Bid Fulfillment/PlaceBidViewController.swift
- Kiosk/HelperFunctions.swift
- KioskTests/Bid Fulfillment/KeypadViewModelTests.swift
- KioskTests/Bid Fulfillment/PlaceBidNetworkModelTests.swift
- KioskTests/Bid Fulfillment/PlaceBidViewControllerTests.swift
- KioskTests/Models/BidTests.swift
- KioskTests/Models/BidderPositionTests.swift
Work for https://github.com/artsy/auctions/issues/301
> Converts to UInt64 for currency

- CHANGELOG.yml
- Kiosk/App/Models/SaleArtwork.swift
- Kiosk/App/Models/SaleArtworkViewModel.swift
- Kiosk/Auction Listings/MasonryCollectionViewCell.swift
- Kiosk/Bid Fulfillment/PlaceBidViewController.swift
- Kiosk/ListingsCollectionViewCell.swift
- Kiosk/Observable+Operators.swift
- Kiosk/Sale Artwork Details/SaleArtworkDetailsViewController.swift
- KioskTests/Bid Fulfillment/PlaceBidViewControllerTests.swift
- KioskTests/ListingsViewControllerTests.swift
- KioskTests/SaleArtworkDetailsViewControllerTests.swift
This PR is related to work on eigen: https://github.com/artsy/eigen/pull/2244 to fix this issue: https://github.com/artsy/auctions/issues/333
> Moves to lot_label

- CHANGELOG.yml
- Kiosk/App/Models/SaleArtworkViewModel.swift
- Kiosk/App/SwiftExtensions.swift
- Kiosk/Bid Fulfillment/BidDetailsPreviewView.swift
- Kiosk/Bid Fulfillment/PlaceBidViewController.swift
> Fixes compiler warnings on casting.

- Kiosk/Admin/ChooseAuctionViewController.swift
- Kiosk/Storyboards/Auction.storyboard
We have enough sales that it needs to scroll now :tada:
> Uses ORStackScrollView for sale list.

- README.md
> Adds note about enclosures.

- fastlane/Fastfile
> Updates oss lane.

- fastlane/Fastfile
Fixes #691. Also [fixed the Fastlane docs](https://github.com/fastlane/fastlane/pull/12559).
> Fixes OSS installs.

- Kiosk/App/Models/Sale.swift
- KioskTests/Fixtures/SaleFixture.swift
Follow up to #698 based on the Gravity PR: https://github.com/artsy/gravity/pull/11990
We updated the Gravity field name, so we need to update it here too.
> Updates flag name #trivial

- CHANGELOG.yml
- Kiosk/App/Networking/ArtsyAPI.swift
Relates to: https://artsyproduct.atlassian.net/browse/PURCHASE-935
> Update oauth call to use post

- Podfile
https://github.com/stripe/stripe-ios/issues/1525
> xcode 11.4 compatibility update

- Podfile
> Runs tests for OSS PR
